addons:
  apt:
    packages:
    - nodejs
language: python
sudo: false
python:
  - 3.5
env:
  - TOX_ENV=csslint
  - TOX_ENV=eslint
  - TOX_ENV=pycodestyle
  - TOX_ENV=pylint
  - TOX_ENV=py35-django111
  - TOX_ENV=py35-django20
  - TOX_ENV=py35-django21
  - TOX_ENV=py35-django22
before_install:
  - "pip install -U pip"
  - export BOTO_CONFIG=/dev/null
cache:
    directories:
        - $HOME/.cache/pip
install:
  - "make requirements"
  - "pip install codecov"
script:
  - tox -e $TOX_ENV
branches:
    only:
      - master
after_success: codecov
