# Generated by Django 2.2.13 on 2021-08-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualtricssurvey', '0004_remove_surveystatus_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyStatus',
        ),
    ]
