# Generated by Django 4.2.19 on 2025-07-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualtricssurvey', '0005_delete_surveystatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QualtricsSubscriptions',
        ),
    ]
